<!DOCTYPE html>

<!--[if lt IE 7]>
<html class="lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>
<html class="lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>
<html class="lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en"><!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <?php /** @noinspection PhpUndefinedMethodInspection */
    echo $this->headTitle('TrksRecipeDoc')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width,initial-scale=1.0') ?>

    <style>
        body
        {
            font-family: sans-serif;
            background: #202020;
            color: #fff;
            font-size: 0.8em;
        }

        table tr.odd td
        {
            background: #282828;
        }

        table.navbox th
        {
            background: #004B71;
            color: #fff;
            font-weight: bold;
        }

        a, a:visited, .mw-body a:visited
        {
            color: #0088CC;
        }

        a
        {
            background: none repeat scroll 0 0 rgba(0, 0, 0, 0);
            text-decoration: none;
        }

        a:hover
        {
            text-decoration: underline;
        }

        .crafting
        {
            width: 512;
            height: 512px;
            position: relative;
            margin: 10px;
            float: left;
        }

        .crafting .handler
        {
            text-align: center;
            width: 512px;
            color: #222;
            font-size: 20px;
            position: absolute;
            top: 20px;
        }

        .crafting .ingredient
        {
            position: absolute;
        }


    </style>
</head>