<?php /* @var $this \Trks\View\TrksPhpRenderer */ ?>
<!DOCTYPE html>

<!--[if lt IE 7]>
<html class="lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>
<html class="lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>
<html class="lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en"><!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <?php /** @noinspection PhpUndefinedMethodInspection */
    echo $this->headTitle('TrksRecipeDoc')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width,initial-scale=1.0') ?>

    <?= $this->headLink()->appendStylesheet('/style.css', 'screen', null, null); ?>
    <?= $this->headScript()->appendFile('/js/jquery-2.0.3.min.js'); ?>
</head>