<?php
/* @var $this \Trks\View\TrksPhpRenderer */
/* @var $recipe \Recipe */
$handler = \RecipeDoc\Model\RecipeDocData::getInstance()->getRecipeHandler($recipe->recipeHandler);
?>
<div class="crafting">
    <img src="/images/recipebg.png"/>
    <img src="/images/gui_backgrounds/<?= $handler->image ?>" style="position:absolute; left: 2px; top: 47px;"/>

    <div class="handler"><?= $handler->name; ?></div>
    <?php foreach ($recipe->ingredients as $ingredient): ?>
        <?php $itemId = $ingredient->items[0]; ?>
        <?php $item = \RecipeDoc\Model\RecipeDocData::getInstance()->getItem($itemId->id, $itemId->damage); ?>
        <a
            class="ingredient"
            style="left:<?= $ingredient->x * 2.9 + 20; ?>px; top: <?= $ingredient->y * 2.9 + 50; ?>px;"
            href="<?=$this->url("main", array(
                'controller' => 'Home',
                'action' => 'item',
                'id' => $itemId->id,
                'id2' => $itemId->damage
            )); ?>"
            title="<?= $item ? $item->name : "unknown"; ?>"
        >
            <?php if ($item): ?>
                <img src="/images/icons/<?= $item->icon; ?>" style="height: 40px; width: 40px;"/>
            <?php else: ?>
                <img style="padding-left:10px;padding-top:10px;" src="/images/icon_unknown.png" />
            <?php endif; ?>
            <?php if ($ingredient->type == \RecipeDoc\Model\RecipeDocData::RECIPE_ITEM_TYPE_RESULT || $ingredient->amount > 1): ?>
                <div class="ingredient_amount">
                    <?= $ingredient->amount; ?>
                </div>
            <?php endif; ?>
        </a>
    <?php endforeach; ?>
</div>