<table style="height: 100%; margin: 0 auto;">
    <tr>
        <td style="vertical-align: middle;">
            <h1 style="text-align: center; font-size: 50px;">404</h1>
            <p style="font-size: 50px;">
                <?= $this->message; ?>
                <?php if (T_DEBUG): ?>
                    <?= $this->render("_part/404_debug.phtml"); ?>
                <?php endif ?>
            </p>
        </td>
    </tr>
</table>
<script type="text/javascript">
    $("body").css("height", "100%");
    $("html").css("height", "100%");
</script>

<?php if (T_DEBUG): ?>



<?php endif ?>