<?php
    /* @var $this \Trks\View\TrksPhpRenderer */
    $odd = true;
?>
<?php foreach (\RecipeDoc\Model\RecipeDocData::getInstance()->getGroupedItems() as $mod => $categories): ?>
    <?php if ($mod == 'Minecraft') continue; ?>
    <table style="width:100%;" class="navbox">
        <tr><th colspan="2"><?= $mod; ?></th></tr>

        <?php foreach ($categories as $category => $items): ?>
            <tr>
                <th style="width:10%;"><?= $category; ?></th>
                <td>
                    <table style="width:100%;">
                    <tr class="<?= $odd ? 'odd' : ''; ?>" style="width:100%;">
                        <?php $i = 0; ?>
                        <?php $odd = !$odd; ?>
                        <?php foreach ($items as $item): ?>
                            <?php if ($i == 4): ?>
                                </tr><tr class="<?= $odd ? 'odd' : ''; ?>">
                                <?php $i = 0; ?>
                                <?php $odd = !$odd; ?>
                            <?php endif; ?>
                            <?php /* @var \Item $item */ ?>
                            <td style="width:25%;">
                                <a href="<?= $this->url("main", array(
                                    'controller' => 'Home',
                                    'action' => 'item',
                                    'id' => $item->id,
                                    'id2' => $item->damage
                                )); ?>">
                                    <img src="images/icons/<?= $item->icon; ?>" width="16px" height="16px"> <?= $item->name; ?>
                                </a>
                            </td>
                            <?php $i++; ?>
                        <?php endforeach; ?>
                        <?php for (; $i < 4; $i++) echo "<td></td>"; ?>
                    </tr>
                    </table>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endforeach; ?>
